#!/bin/sh

## Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K\r'
CLEAR_SCREEN='\033c'

PUM_DIR=~/pum

# Check is project exists
if [ -d ~/pum ]; then 
  cd ~/pum
  if ! git status 2>&1 | grep -i 'not a git repository' > /dev/null ; then
    echo "${GREEN}✔ pum already cloned${NO_COLOR}"
  fi
else
  # No project
  mkdir -p ~/pum

  if ! [ -x "$(command -v curl)" ]; then
    echo "${YELLOW}⚠ Not found curl${NO_COLOR}"
    echo "Installing curl"
    apt update
    apt install curl
  fi


  echo "📦 Cloning project..."
  cd ~/pum
  git clone git@github.com:nitpum/pum.git ~/pum
fi

cd ~/

# Create symlink to bin
if [ -L ~/bin/pum ]; then
  echo "${GREEN}✔ Launcher already setup${NO_COLOR}"
else
  echo "🚀 Setup launcher file..."
  mkdir -p ~/bin
  ln -s ~/pum/pum ~/bin/pum
  chmod +x ~/pum/pum
fi

cd ~/

if grep -E "source $PUM_DIR/profile" .profile > /dev/null; then
  echo "${GREEN}✔ Profile already setup${NO_COLOR}"
else
  echo "😀 Setup profile"

  echo "\nsource $PUM_DIR/profile" >> ~/.profile
fi

if grep -E "source $PUM_DIR/profile" .bashrc > /dev/null; then
  echo "${GREEN}✔ Bash profile already setup${NO_COLOR}"
else
  echo "📜 Setup bash profile"

  echo "\nsource $PUM_DIR/profile" >> ~/.bashrc
fi

# Install starship
# echo "🚀 Install starship"
# sh -c "$(curl -fsSL https://starship.rs/install.sh)"

# # Install golang
# echo "🤖 Install go"
# apt install golang-go

# # Install powerline
# echo "Install powerline"
# go get -u github.com/justjanne/powerline-go