#/bin/bash

# ===================
# NOTE: Do not edit this file
# Update in main.sh instead, This file uses to be proxy
# so this file can be copy or be symbolic link 
#
# Default location: ~/bin/pum.sh
#
# ===================

source ~/pum/main